services:
  db:
    image: postgres:16.11-alpine3.23
    container_name: sakura-ai-bot-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: botdb
    ports:
      - "5432:5432"
    networks:
      - shared-sakura-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d botdb"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  app:
    build: .
    networks:
      - shared-sakura-db
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      OWNER_ID: ${OWNER_ID}
      LOAD_SESSION_DELAY: ${LOAD_SESSION_DELAY}
      CHECK_MAIL_DELAY: ${CHECK_MAIL_DELAY}
      MAX_SAKURA_SESSIONS: ${MAX_SAKURA_SESSIONS}
      MAX_INVALID_REQUEST_COUNT: ${MAX_INVALID_REQUEST_COUNT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  shared-sakura-db:
    name: shared-sakura-db
